# action.yml
name: 'Update Partner Center offer artifact'
description: 'Update Partner Center offer artifact'
inputs:
  token:
    description: 'Authentication token of Partner Center'
    required: true
  offerName:
    description: 'Offer name'
    required: true
  planName:
    description: 'Plan name'
    required: true
  filePath:
    description: 'Artifact file path'
    required: true
  artifactVersion:
    description: 'Artifact version'
    required: true
    default: '1.0.0'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }} 
    - ${{ inputs.offerName }} 
    - ${{ inputs.planName }} 
    - ${{ inputs.filePath }} 
    - ${{ inputs.artifactVersion }}